Repository shabados/docs, pull requests merged in 2021-03, with the labels that each got.

#50 ci: setup danger js to lint PR titles
  .github/workflows/danger.yml
  commitlint.config.js
  dangerfile.js
  package-lock.json
  package.json
Labels: Effort: 5 pts, Impact: Avg, Status: Merge, Type: Build

#64 ci: run on `pull_request_target`
  .github/workflows/danger.yml
Labels: Effort: 0 pt, Impact: High, Status: Merge

#66 feat: add article for live streaming with streamlabs
  content/presenter/guides/configuring-live-stream-captions.md
Labels: Effort: 1 pt, Impact: Low, Status: Merge, Type: Feat

#65 fix: change minor thematic issues
  content/database/source-material.md
  src/css/custom.css
Labels: Effort: 1 pt, Impact: Avg, Status: Merge, Type: Fix

#68 build: update package-lock
  package-lock.json
Labels: Effort: 0 pt, Impact: Crit, Status: Merge, Type: Build

#67 feat: add viewer articles
  content/database/index.md
  content/tutorials/index.md
  content/tutorials/overlay/create-custom-theme.md
  content/tutorials/overlay/get-started.md
  content/tutorials/overlay/index.md
  content/tutorials/viewer/proofreading.md
  content/viewer/guides/proofreading.md
  content/viewer/index.md
  docusaurus.config.js
  src/pages.config.js
  src/sidebars/tutorials.js
  src/sidebars/viewer.js
  static/img/proofreading-difference-submit-proofreading-ticket.png
Labels: Effort: 5 pts, Impact: Low, Status: Merge, Type: Feat

#63 feat: add article guide for zoom closed captioning
  content/presenter/guides/integrating-closed-captioning-in-zoom-meetings.md
  src/css/custom.css
  src/sidebars/presenter.js
  static/img/shabados-zoom-panel.png
  static/img/zoom-meeting-controls-closed-caption.png
  static/img/zoom-settings-closed-captioning.png
Labels: Effort: 1 pt, Impact: Avg, Status: Merge, Type: Feat

#70 ci: run build
  .github/workflows/ci.yml
  content/presenter/reference/url-endpoints.md
Labels: Effort: 0 pt, Impact: Crit, Status: Merge
