Repository shabados/docs, pull requests merged in 2021-02, with the labels that each got.

#22 docs: update readme release badges
  README.md
Labels: Effort: 0 pt, Impact: Low, Status: Merge, Type: Fix

#23 feat(frontend): update styles to be more modern
  docusaurus.config.js
  src/css/custom.css
Labels: Effort: 1 pt, Impact: Crit, Status: Merge, Type: Feat

#25 feat(frontend): remove footer
  docusaurus.config.js
  src/css/custom.css
Labels: Effort: 0 pt, Impact: Avg, Status: Merge, Type: Fix

#29 feat: remove docs route
  docs/index.md
  docusaurus.config.js
Labels: Effort: 0 pt, Impact: Low, Status: Merge, Type: Feat

#28 build: update dependencies
  package-lock.json
  package.json
Labels: Effort: 0 pt, Status: Merge, Type: Build

#33 fix(frontend): target css of sidebar appropriately
  src/css/custom.css
Labels: Effort: 0 pt, Impact: Crit, Status: Merge, Type: Fix

#34 feat: remove announcement bar
  docusaurus.config.js
Labels: Effort: 0 pt, Impact: Avg, Status: Merge, Type: Feat

#39 build: configure docusaurus for algolia
  docusaurus.config.js
Labels: Effort: 0 pt, Impact: Crit, Status: Merge, Type: Build

#30 docs: rehaul database docs for docusaurus
  .vscode/extensions.json
  .vscode/settings.json
  content/database/index.md
  content/database/installation.md
  content/database/installing-or-accessing.md
  content/database/schema.md
  content/database/schema/bani_lines.md
  content/database/schema/banis.md
  content/database/schema/compositions.md
  content/database/schema/languages.md
  content/database/schema/line_content.md
  content/database/schema/line_types.md
  content/database/schema/lines.md
  content/database/schema/overview.md
  content/database/schema/sections.md
  content/database/schema/shabads.md
  content/database/schema/sources.md
  content/database/schema/subsections.md
  content/database/schema/translation_sources.md
  content/database/schema/translations.md
  content/database/schema/transliterations.md
  content/database/schema/writers.md
  content/database/source-material.md
  src/css/custom.css
  src/sidebars/database.js
Labels: Effort: 5 pts, Impact: Avg, Status: Merge, Type: Docs

#44 feat: make ToC more readable with a title and bolded active items
  src/css/custom.css
Labels: Effort: 0 pt, Impact: Low, Type: Feat

#46 feat: remove illogical pagination buttons
  src/css/custom.css
Labels: Effort: 0 pt, Impact: Low, Status: Merge, Type: Feat

#42 build: remove commitlint and husky
  .huskyrc.json
  commitlint.config.js
  package-lock.json
  package.json
Labels: Effort: 0 pt, Impact: Crit, Type: Build

#48 fix: use hexcode for border colors instead of rgba
  src/css/custom.css
Labels: Effort: 0 pt, Impact: High, Status: Merge, Type: Fix

#43 feat: create a useable home/front page
  docusaurus.config.js
  src/css/custom.css
  src/pages/index.js
Labels: Effort: 1 pt, Impact: High, Status: Merge, Type: Feat

#51 feat: migrate presenter docs
  content/presenter/guides/configuring-live-stream-captions.md
  content/presenter/guides/installing-shabad-os-presenter.md
  content/presenter/guides/using-google-chrome-to-chromecast-shabad-os.md
  content/presenter/index.md
  content/presenter/reference/url-endpoints.md
  content/tutorials/chromecast.md
  content/tutorials/images/google-chrome-cast-button.png
  content/tutorials/images/google-chrome-resizing-info.png
  content/tutorials/images/google-chrome-undock-devtools.png
  content/tutorials/install.md
  content/tutorials/overlay/add-livestream-captioning.md
  content/tutorials/overlay/get-started.md
  content/tutorials/url-endpoints.md
  content/tutorials/viewer/proofreading.md
  src/pages.config.js
  src/sidebars/presenter.js
  src/sidebars/tutorials.js
  static/img/add-browser-obs-studio.png
  static/img/add-browser-vmix.png
  static/img/ip-address-windows-task-manager.png
  static/img/proofreading-difference-example-browser.png
  static/img/proofreading-difference-example-pdf.png
  static/img/proofreading-example-copy-snip-and-sketch.png
  static/img/proofreading-example-insert-cursor-gh-issue.png
  static/img/proofreading-example-paste-image-gh-issue.png
  static/img/settings-overlay-url.png
  static/img/shabados-about-url.png
  static/img/smartscreen.jpg
  static/img/wirecast-add-web-page.png
  static/img/wirecast-shot-layer-properties.png
  static/img/wirecast-source-properties.png
Labels: Effort: 5 pts, Impact: High, Status: Merge, Type: Feat

#52 fix: change broken css from rgba to hex
  src/css/custom.css
Labels: Effort: 0 pt, Impact: Avg, Status: Merge, Type: Fix

#56 fix: use static links for articles
  content/community/project-management.md
  content/database/index.md
  content/database/installing-or-accessing.md
  content/database/schema/bani_lines.md
  content/database/schema/banis.md
  content/database/schema/line_content.md
  content/database/schema/line_types.md
  content/database/schema/lines.md
  content/database/schema/overview.md
  content/database/schema/sections.md
  content/database/schema/shabads.md
  content/database/schema/sources.md
  content/database/schema/subsections.md
  content/database/schema/translation_sources.md
  content/database/schema/translations.md
  content/database/schema/transliterations.md
  content/database/usage/index.md
  content/presenter/guides/configuring-live-stream-captions.md
  content/presenter/index.md
  content/presenter/reference/url-endpoints.md
  content/tutorials/index.md
  content/tutorials/overlay/create-custom-theme.md
  content/tutorials/overlay/get-started.md
  src/pages/index.js
Labels: Effort: 1 pt, Impact: Low, Status: Merge, Type: Fix

#57 fix: update algolia configuration
  docusaurus.config.js
  package-lock.json
  package.json
  src/css/custom.css
  src/pages/index.js
Labels: Effort: 1 pt, Impact: Avg, Status: Merge, Type: Fix
