Repository shabados/docs, pull requests merged in 2021-06, with the labels that each got.

#75 feat: add an article on importing an overlay theme
  content/presenter/guides/importing-an-overlay-theme.md
  src/sidebars/presenter.js
Labels: Effort: 0 pt, Impact: Low, Type: Feat

#79 fix: update steps in zoom article
  content/presenter/guides/integrating-closed-captioning-in-zoom-meetings.md
Labels: Effort: 0 pt

#80 refactor: make sidebar editing easier
  README.md
  content/community/sidebar.js
  content/database/sidebar.js
  content/presenter/sidebar.js
  content/viewer/sidebar.js
  src/pages.config.js
Labels: Status: Merge

#77 fix: slack url
  content/community/index.md
Labels: Effort: 0 pt, Status: Merge, Type: Fix

#78 fix: edit link url
  src/consts.js
Labels: Effort: 0 pt, Status: Merge, Type: Fix

#81 feat: add trusted source for english translation
  content/database/source-material.md
Labels: Status: Merge
